config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  get "/dashboard", to: "pages#dashboard"
  get "/statistics", to: "pages#statistics"
  resources :attempts
  resources :levelleaderboards
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attempt.rb
class Attempt < ApplicationRecord
  belongs_to :user
  belongs_to :level

  scope :filter_by_level, -> (level) { where level: level }
  # validates :total_time, :problems_solved, :score, presence: true
  # validates :total_time, numericality: { only_integer: true, greater_than: 0 }
  # validates :problems_solved, numericality: { only_integer: true,
                                              # greater_than_or_equal_to: 0 }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :levels

  validates :name, presence: true
  validates :name, length: { minimum: 3, maximum: 50 }
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :category
  has_many :attempts

  validates :name, :total_problems, presence: true
  validates :name, length: { minimum: 3, maximum: 36 } # e.g. a guid is 36 characters long
  validates :total_problems, numericality: { only_integer: true, greater_than: 0 }

  def name_for_select
    name.capitalize
  end
end

app/models/levelleaderboard.rb
class Levelleaderboard < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attempts

  validates :first_name, :last_name, length: { minimum: 2, maximum: 50 }
  validates :nickname, length: { minimum: 3, maximum: 15 }
  validates :first_name, :last_name, :email, :dob, presence: true
end

app/models/user_level.rb
class UserLevel
  def initialize(level, attempts)
    @attempts = attempts
    @level = level
  end

  def level_name
    @level.name
  end

  def category_name
    @level.category.name
  end

  def level_id
    @level.id
  end

  def best_time
    return "NA" if @attempts.nil?

    @all_time = @attempts.map(&:total_time).compact
    return "NA" if @all_time.count.zero?

    "#{@all_time.min / 1000.0} secs"
  end

  def attempts_count
    @attempts.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name nickname dob])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name nickname dob])
  end

  def after_sign_in_path_for(_resource)
    dashboard_path
  end
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  before_action :set_attempt, only: %i[show update ]

  def index
    @level = Level.find_by_id(params[:level])
    if @level
      @attempts = Attempt.where(user: current_user)
                         .and(Attempt.where.not(total_time: nil))
                         .filter_by_level(@level)
                         .order(id: :desc)
    else
      @attempts = Attempt.where(user: current_user)
                         .and(Attempt.where.not(total_time: nil))
                         .order(id: :desc)
    end
    @all_time = @attempts.map(&:total_time).compact
    @total_problems = @attempts.map(&:problems_solved).compact
    @all_scores = @attempts.map(&:score).compact
    @all_bullets = @attempts.map(&:bullets_fired).compact

    @levels = Level.all
  end

  def new
    level = Level.find_by_id(params[:level_id])
    level = Level.last if level.nil?

    attempt = Attempt.create(level: level, user: current_user)

    redirect_to "/game/index.html?a=#{attempt.id}", status: 302
  end

  def show
    @attempt = Attempt.find(params[:id])
    render json: @attempt.to_json(include: %i[user level])
  end

  def create; end

  def update
    @attempt.update(attempt_params)
    render json: @attempt.to_json(include: %i[user level])
  end

  private

  def set_attempt
    @attempt = Attempt.find(params[:id])
  end

  def attempt_params
    params.require(:attempt).permit(:total_time, :score, :problems_solved, :bullets_fired)
  end
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  def completed_tasks
    render json: Attempt.group(:score).group_by_day(:created_at).count.chart_json
  end
  def index
  end
end

app/controllers/levelleaderboards_controller.rb
class LevelleaderboardsController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
    @users = User.all
  end

  def dashboard
    @levels = Level.all
    @user_levels = []

    @levels.each do |level|
      @level_attempts = Attempt.where(user: current_user, level: level).and(Attempt.where.not(total_time: nil))
      @user_level = UserLevel.new(level, @level_attempts)
      @user_levels << @user_level
    end
  end

  def statistics
    @levels = Level.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/attempts/index.html.erb
<div class="container">
  <%= render "shared/tabs" %>
    <turbo-frame id="attempts">
      <%= render "shared/filter" %>
      <%= render "shared/stats_card" %>
      <%= render "shared/attempt_table" %>
    </turbo-frame>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <link rel="shortcut icon" type="image/png"
      href="https://math-mavens.fly.dev/images/logo.png"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"/>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
  <%= render "shared/flashes" %>

    <%= yield %>
      <%= render "shared/footer" %>

    <script>
      const observer = new IntersectionObserver(entries => {
        entries.forEach(entry => {
          // console.log(entry);
          const animElement = entry.target.querySelector('.anim-element');
          const animType = animElement.dataset.animType;
          const animRepeat = animElement.dataset.animReps;

          // console.log('type ' + animType);

          if (entry.isIntersecting) {
            // console.log("adding...");
            // console.log(animElement);
            animElement.classList.add('animate__animated', animType,
                                      animRepeat);
            return; // if we added the class, exit the function
          }

          // We're not intersecting, so remove the class!
          // console.log("removing...");
          animElement.classList.remove('animate__animated', animType,
                                      animRepeat);
        });
      });

      const allAnimWrappers = document.querySelectorAll('.anim-wrapper');
      console.log(allAnimWrappers);
      allAnimWrappers.forEach(wrapper => {
        observer.observe(wrapper);
      });


    </script>
  </body>
</html>

app/views/levelleaderboards/index.html.erb
<div class="container my-4">
  <div>
  <section id="levelleaderboard">
    <nav class="ladder-nav-lvl">
      <div class="ladder-title-lvl">
      <h1>Leaderboard</h1>
      </div>
      <div class="ladder-search-lvl">
        <input type="text" id="search-leaderboard-lvl" class="live-search-box" placeholder="Search A User..." />
      </div>
    </nav>
    <table id="rankings" class="leaderboard-results-lvl" width="100%">
      <thead>
        <tr class="th-text">
          <th>Rank</th>
          <th>Nickname</th>
          <th>Time taken</th>
          <th>Problems solved</th>
          <th>Bullets fired</th>
          <th class="score-bold">Score</th>
        </tr>
      </thead>
      <tbody class="rows-lvl">
        <% @users.each do |user| %>
          <%if user.id == current_user.id %>
            <tr class="user-row-color">
          <% else %>
            <tr>
          <% end %>
            <td><%= user.id %></td>
            <td><%= user.nickname %></td>
            <td>55 seconds</td>
            <td>5</td>
            <td>90</td>
            <td class="score-bold">3500</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </section>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class="container">
    <%= render "shared/tabs" %>
    <%= render "shared/gamecard" %>
</div>

app/views/pages/home.html.erb
<%= render "shared/banner" %>
<%= render "shared/hiw-cards" %>
<%= render "shared/details-section" %>
<%= render "shared/progress_section" %>

app/views/pages/statistics.html.erb
<div class="container">
    <%= render "shared/tabs" %>
    <div class="text-center my-4">
      <h1>Here's how well you are doing!</h1>
      <p>Analyze your data and results in differents mathematics operations to target where you need to train more.<br>Math Mavens helps you to gain fluency and confidence in math.</p>
    </div>
    <div class="my-4">
      <!-- <div>
        <h3 style="font-size: 24px;" class="text-center my-4">Attempts per day</h3>
        <%# <%= line_chart @levels.map { |level|
          {name: level.name, data: Attempt.feats.group_by_day(:created_at).count}
        } %>
      </div> -->
      <div class="my-5">
        <h3 style="font-size: 24px" class="text-center">Your recent attempts</h3>
        <%= column_chart Attempt.group_by_hour(:updated_at, format: "%a %l%p", range: 2.days.ago.midnight..Time.now).count, points: false, label: "Value", colors: ["#F06D4F", "#F06D4F"], ytitle: "Total attempts", empty: "No data"  %>
      </div>
      <div class="my-5">
        <h3 style="font-size: 24px;" class="text-center">Best scores</h3>
        <%= area_chart Attempt.group_by_hour(:updated_at, format: "%a %l%p", range: 2.days.ago.midnight..Time.now).sum(:score), colors: ["#F06D4F", "#F06D4F"], ytitle: "Total score" %>
      </div>
      <div class="my-5">
        <h3 style="font-size: 24px;" class="text-center">Your best times</h3>
        <%= column_chart Attempt.group_by_hour(:updated_at, format: "%a %l%p", range: 2.days.ago.midnight..Time.now).minimum(:total_time), colors: ["#F06D4F", "#F06D4F"], ytitle: "Time taken" %>
      </div>
      <div class="my-5">
        <h3 style="font-size: 24px;" class="text-center">How many bullets did you fire</h3>
        <%= area_chart Attempt.group_by_hour(:updated_at, format: "%a %l%p", range: 2.days.ago.midnight..Time.now).sum(:bullets_fired), colors: ["#F06D4F", "#F06D4F"], ytitle: "Total bullets fired" %>
      </div>
    </div>
</div>

app/views/shared/_aggregate_table.html.erb
<div class="container-wrap my-5 border rounded-4">
	<section id="leaderboard">
		<nav class="ladder-nav">
			<div class="ladder-title">
			<h1>Your Statistics</h1>
			</div>
			<div class="ladder-search">
				<%# <input type="text" id="search-leaderboard" class="live-search-box" placeholder="Search Your Attempts..." /> %>
			</div>
		</nav>
		<table id="rankings" class="leaderboard-results" width="100%">
			<thead>
				<tr>
					<th>No. of Attempts</th>
					<th>Total Time Played</th>
					<th>Total Problems Solved</th>
					<th>Total Levels Played</th>
				</tr>
			</thead>
			<tbody>
				<td><%= @attempts.count  %></td>
				<td><%= (@all_time.sum / 1000) %> seconds</td>
				<td><%= @total_problems.sum %></td>
				<td><%= @attempts.count %></td>
			</tbody>
		</table>
	</section>
  </div>

app/views/shared/_attempt_table.html.erb
<div class="container">
  <div class="my-4 border rounded-4">
      <section id="leaderboard scrollbar">
        <nav class="ladder-nav">
          <div class="ladder-title">
          <h1>Your Attempts</h1>
          </div>
        </nav>
        <div style="height: auto; overflow:auto;">
          <table id="rankings" class="leaderboard-results" width="100%">
            <thead>
              <tr>
                <th id="level-name">Level</th>
                <th>Attempt No.</th>
                <th>Time Taken</th>
                <th>Problems Solved</th>
                <th>Bullets Fired</th>
                <th>Score</th>
              </tr>
            </thead>
            <tbody class="rows-color table-attempts">
            <% @attempts.each do |attempt| %>
            <tr>
              <td><%= attempt.level.name.capitalize %></td>
              <td><%= attempt.id.nil? ? 0 : attempt.id %></td>
              <td><%= attempt.total_time.nil? ? 0 : attempt.total_time/1000.0 %> secs</td>
              <td><%= attempt.problems_solved.nil? ? 0 : attempt.problems_solved %></td>
              <td><%= attempt.bullets_fired.nil? ? 0 : attempt.bullets_fired %></td>
              <td><%= attempt.score.nil? ? 0 : attempt.score.round %> pts</td>
            </tr>
            <% end %>
            </tbody>
          </table>
        </div>
    </section>
  </div>
</div>

app/views/shared/_banner.html.erb
<div class="banner 80-vh">
  <div class="container height: auto;">
    <div class="row">
      <div class="col-6">
        <h2 class="mb-2">Raise a</h2>
          <div class="anim-wrapper">
            <h1 class="anim-element" data-anim-type="animate__pulse"
              data-anim-reps="animate__repeat-2">Math-A-Magician!</h1>
          </div>
        <p>Your child can now train their math skills and have fun! Our training programs include addition, subtraction, multiplication and division. Get your child to play through our array of levels. Specially curated to improve their mental math skills!</p>
        <a class="btn prm-button" href="/dashboard">Get Started</a>
      </div>
      <div class="col-6 d-flex justify-content-center">
      <%= image_tag "https://math-mavens.fly.dev/images/banner-img-family.jpeg", class: "mt-4" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_filter.html.erb
 <div class="container">
  <div class="ladder-search">
    <%= form_tag attempts_path, method: 'get', class: 'd-flex justify-content-end' do %>
      <%= select_tag :level,
        options_from_collection_for_select(@levels, 'id', :name_for_select, params[:level]),
        include_blank: 'All Levels', class: 'justify-content-end form-select w-25 me-1' %>
      <%= submit_tag 'Filter', class: 'btn btn-primary text-white' %>
    <% end %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_gamecard.erb
<div class="container my-3">
  <h2 class="my-4 text-center">Math Invaders</h2>
  <div class="col-md-12 ml-auto mr-auto">
    <div class="group-cards">
      <div class="row flex-row justify-content-center gap-4">
        <!-- CARD -->
        <% @user_levels.each_with_index do |user_level, index| %>
          <div class="col-lg-3 col-md-6 col-sm-12 mb-1 px-0">
            <div class="card-game">
              <img src="https://math-mavens.fly.dev/images/<%= index + 1 %>.png" alt="">
              <div class="card-body">
                <h5><%= user_level.level_name.capitalize %></h3>
                <div class="mt-3">
                  <div class="row">
                    <div class="col"><i class="fa-solid fa-stopwatch"></i>&nbsp;&nbsp;Best Time:</div>
                    <div class="col text-warning"><h6><%= user_level.best_time %></h6></div>
                  </div>
                  <div class="row">
                    <div class="col"><i class="fa-solid fa-list-check"></i>&nbsp;&nbsp;Attempts:</div>
                    <div class="col text-warning"><h6><%= user_level.attempts_count %></h6></div>
                  </div>
                </div>
                <div class="d-flex justify-content-between align-items-center mt-3">
                  <div>
                    <%= link_to "Play 🎮",
                    new_attempt_path(level_id: user_level.level_id),
                    class: "btn btn-primary text-white",
                    data: { turbo: false } %>
                  </div>
                  <div class="badge bg-secondary"><%= user_level.category_name %></div>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_hiw-cards.erb
<div class="container space-section">
  <div class="section-title col-lg-8 col-md-10 mx-auto">
    <h2 class="text-center">How it works</h2>
    <p class="text-center text-desc-home">Math Mavens is built to help your kids love mathematics. We have four categories: addition, substraction, multiplication and division. Theses categories will help to improve their mathematics knowledge and become better and better everyday. Let’s start by picking up a category and play!</p>
  </div>
  <div class="col-md-12 ml-auto mr-auto">
    <div class="row">
    <!-- CARD -->
      <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
        <div class="card-hiw">
          <img src="https://images.pexels.com/photos/5200773/pexels-photo-5200773.jpeg?auto=compress&cs=tinysrgb&w=800" alt="">
          <div class="card-body">
            <div class="d-flex hiw-numb gap-2">
                <div class="anim-wrapper">
                  <h2 class="number-hiwcard anim-element"
                    data-anim-type="animate__fadeInLeftBig" data-anim-reps="animate__repeat-1">01.</h2>
                </div>
              <h2>Choose a game</h2>
            </div>
            <p>Start their math journey by choosing a math category. You can choose between our four main categories.</p>
          </div>
        </div>
      </div>
       <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
        <div class="card-hiw">
          <img src="https://images.pexels.com/photos/5896689/pexels-photo-5896689.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="">
          <div class="card-body">
            <div class="d-flex hiw-numb gap-2">
                <div class="anim-wrapper">
                  <h2 class="number-hiwcard anim-element"
                    data-anim-type="animate__fadeInDownBig" data-anim-reps="animate__repeat-1">02.</h2>
                </div>
              <h2>Play</h2>
            </div>
            <p>Let your child play our different categories and try to achieve the best scores possible. Your child can attempt each level as many times as they'd like.</p>
          </div>
        </div>
      </div>
       <div class="col-lg-4 col-md-6 col-sm-12 mb-4">
        <div class="card-hiw">
          <img src="https://images.pexels.com/photos/5896665/pexels-photo-5896665.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" alt="">
          <div class="card-body">
            <div class="d-flex hiw-numb gap-2">
                <div class="anim-wrapper">
                  <h2 class="number-hiwcard anim-element"
                    data-anim-type="animate__fadeInRightBig" data-anim-reps="animate__repeat-1">03.</h2>
                </div>
              <h2>Repeat</h2>
            </div>
            <p>The main goal of Math Mavens is to make your child the best mathematician possible. Train and repeat to become a Math-A-Magician!</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_leaderboard.html.erb
<div class="container space-section">
  <div class="text-center">
    <h2 >Keep playing until you get better by tracking your attempts</h2>
    <p style="margin-bottom: 40px; margin-top: 20px;" class="text-desc-home">Start playing in our different categories to train your math skills.<br>You can track your progress on your dashboard page with statistics based on your past games.</p>
  </div>
  <section id="levelleaderboard">
    <div>
      <h3 style="font-size: 24px;" class="text-center my-4">Attempts per day</h3>
      <%= area_chart Attempt.group_by_day(:created_at).count, colors: ["#F06D4F", "#F06D4F"], xtitle: "Day", ytitle: "Total attempts", empty: "No data"  %>
    </div>
    <div>
      <h3 style="font-size: 24px;" class="text-center my-4">Total score per day</h3>
      <%= area_chart Attempt.group_by_day(:created_at).sum(:score), colors: ["#F06D4F", "#F06D4F"], xtitle: "Day", ytitle: "Total score" %>
    </div>
    <div>
      <h3 style="font-size: 24px;" class="text-center my-4">Best time per day</h3>
      <%= area_chart Attempt.group_by_day(:created_at).minimum(:total_time), colors: ["#F06D4F", "#F06D4F"], xtitle: "Day", ytitle: "Time taken" %>
    </div>
    <div>
      <h3 style="font-size: 24px;" class="text-center my-4">Bullets fired per day</h3>
      <%= area_chart Attempt.group_by_day(:created_at).sum(:bullets_fired), colors: ["#F06D4F", "#F06D4F"], xtitle: "Day", ytitle: "Total bullets fired" %>
    </div>
  </section>
</div>

app/views/shared/_navbar.html.erb
<header class="p-2 navbar-lewagon navbar-mathmavens sticky-top">
    <div class="container">
      <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start gap-4">
       <%= link_to "/", class: "navbar-brand" do %>
        <div class="d-flex">
          <%= image_tag "https://math-mavens.fly.dev/images/logo.png" %><span class="ms-2 fs-3 fw-bolder">Math Mavens</span>
        </div>
       <% end %>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
        <ul class="nav col-12 col-lg-auto mr-4 ms-lg-auto mb-2 justify-content-center mb-md-0 text-navbar">
          <li><%= link_to "Games", dashboard_path, class: "nav-link" %></li>
        </ul>
        <% if user_signed_in? %>
          <div class="text-end">
            <a href="/dashboard" class="btn prm-button-nav me-2">Play</a>
          </div>
          <li class="dropdown" style="list-style: none;">
           <button type="button" class="btn btn-avatar rounded-circle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <div style="height: 25px; width: 13px;"><span style="line-height: 20px;"><%= current_user.nickname[0].capitalize %></span></div>
            </button>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <div class="text-end">
            <%= link_to "Login",  user_session_path, class: "btn button-login me-2" %>
          </div>
        <% end %>
      </div>
    </div>
  </header>

app/views/shared/_progress_section.html.erb
<div class="container mt-5">
  <div class="mw-75 text-center">
    <h1>View progress</h1>
    <div class="mw-50 py-3 px-5">
      <p>Analyze your child's progress and results in differents mathematics operations to target where you need to train more. <br> Math Mavens helps you to gain fluency and confidence in math.</p>
    </div>
    <img src="https://math-mavens.fly.dev/images/attempts_static_chart.png" class="img-fluid" alt="">
  </div>
</div>

app/views/shared/_statistics_tables.html.erb
<h1>Ok</h1>

app/views/shared/_stats_card.html.erb
<div class="container spacing my-4" >
  <div class="flip-card me-3">
    <div class="flip-card-inner">
      <div class="flip-card-front">
        <h1 class="mt-3">Problems Solved</h1>
        <span><i class="fas fa-brain fa-2xl mt-5" style="color:orange"></i></span>
        <p class="mt-4">Your Best: <strong><%= @total_problems.empty? ? 0 : @total_problems.max%></strong></p>
      </div>
      <div class="flip-card-back">
          <p class="mt-5 text-center"> Amazing! Keep going! </p>
        <span><i class="fa-regular fa-thumbs-up fa-2xl" style="color:orange"></i></span>
      </div>
    </div>
  </div>
  <div class="flip-card me-3">
    <div class="flip-card-inner">
      <div class="flip-card-front">
        <h1 class="mt-3">Time Taken</h1>
        <span><i class="fas fa-stopwatch fa-2xl mt-5" style="color:orange"></i></span>
        <p class="mt-4">Your Best: <strong><%= @all_time.empty? ? 0 : @all_time.min/1000.0 %></strong> secs</p>
      </div>
      <div class="flip-card-back">
        <p class="mt-5">Practice makes perfect!</p>
          <span><i class="fa-solid fa-gauge-high fa-2xl" style="color:orange"></i></span>
      </div>
    </div>
  </div>
  <div class="flip-card me-3">
    <div class="flip-card-inner">
      <div class="flip-card-front">
        <h1 class="mt-3">High Score</h1>
        <span><i class="fa-solid fa-award fa-2xl mt-5" style="color:orange"></i></span>
        <p class="mt-4">Your Best: <strong><%= @all_scores.empty? ? 0 : @all_scores.max.to_i %></strong> pts</p>
      </div>
      <div class="flip-card-back">
          <p class="mt-5">You are getting good at this!</p>
        <span><i class="fa-solid fa-chart-line fa-2xl" style="color:orange"></i></span>
      </div>
    </div>
  </div>
  <div class="flip-card">
    <div class="flip-card-inner">
      <div class="flip-card-front">
        <h1 class="mt-3">Bullets Fired</h1>
        <span><i class="fa-solid fa-bullseye fa-2xl mt-5" style="color:orange"></i></span>
        <p class="mt-4">Most: <strong><%= @all_bullets.empty? ? 0 : @all_bullets.max %></strong> shots</p>
      </div>
      <div class="flip-card-back">
          <p class="mt-5">Shoot less aim more!</p>
          <span><i class="fa-solid fa-bars-progress fa-2xl" style="color:orange"></i></span>
      </div>
    </div>
  </div>
</div>